CC = gcc
FLAGS = -std=c11 -pedantic -Wall 

selection:
	$(CC) $(FLAGS) selection_sort.c

bubble:
	$(CC) $(FLAGS) bubble_sort.c

insertion:
	$(CC) $(FLAGS) insertion_sort.c

quick:
	$(CC) $(FLAGS) quick_sort.c

clean:
	rm *.out
